name: Publish Package

on:
  push:
    tags:
      - "*"

permissions:
  id-token: write # Required for OIDC

jobs:
  publish:
    uses: yext/slapshot-reusable-workflows/.github/workflows/publish.yml@v1