name: Publish Package

on:
  push:
    tags:
      - "*"

permissions:
  id-token: write # Required for OIDC

jobs:
  publish:
    uses: anguyen-yext2/slapshot-reusable-workflows-test/.github/workflows/publish.yml@v1