name: Run Linter

on:
  pull_request:
    branches: [main, develop, feature/*]

jobs:
  linting:
    uses: yext/slapshot-reusable-workflows/.github/workflows/run-linting.yml@v1
    with: 
      build_script: |
        npm init @eslint/config
