name: Visual Regression Snapshots

on:
  push:
    branches-ignore: dev/*
  pull_request:

jobs:
  snapshots:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18.x
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run build
      - run: ./tests/scripts/start-storybook.sh
        env:
          MAPBOX_API_KEY: ${{ secrets.MAPBOX_API_KEY }}
      - run: npm run test-snapshots
      - name: Upload snapshot diffs
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: snapshot_diffs
          path: .storybook/snapshots/__snapshots__/__diff_output__/
          retention-days: 30
