name: Sync Main to Storybook Site Branch & Test Site Branch

on:
  push:
    branches:
      - main

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: devmasx/merge-branch@v1.4.0
        with:
          type: now
          from_branch: ${{ github.event.repository.default_branch }}
          target_branch: storybook-site
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - uses: devmasx/merge-branch@v1.4.0
        with:
          type: now
          from_branch: ${{ github.event.repository.default_branch }}
          target_branch: test-site
          github_token: ${{ secrets.GITHUB_TOKEN }}
