name: Sync Main to Storybook Site Branch

on:
  push:
    branches:
      - main
jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Syncing branches
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: mtanzi/action-automerge@v1
        with:
          source: "${{ github.event.repository.default_branch }}"
          target: "storybook-site"
          github_token: ${{ secrets.GITHUB_TOKEN }}
